airflow:
  image:
    repository: puckel/docker-airflow
    tag: 1.10.4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  webReplicas: 1
  config:
    AIRFLOW__CORE__LOGGING_LEVEL: DEBUG
    AIRFLOW__CORE__LOAD_EXAMPLES: False
    AIRFLOW__WEBSERVER__WORKERS: 2
  variables:
    environment: "dev"
  pools:
    example:
      description: "This is an example of a pool"
      slots: 2
workers:
  replicas: 1
  celery:
    instances: 1
persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 1Gi
